In [1]:
import pickle
import tensorflow as tf
import numpy as np
import matrix_decompositions_tf as fctr

In [3]:
fid = open('iter_2_weights.pkl','rb')
output = pickle.load(fid)
fid.close()
dictObj = fctr.dictionary_object2D_init(fftSz = output['fftSz'],D = output['D'],rho = output['rho'],objname = 'dictObj1',n_components = output['n_components'])

In [4]:
tf.reduce_max(tf.math.abs(tf.complex(dictObj.dhmul.Dfreal,dictObj.dhmul.Dfimag) - output['Dfprev']))

<tf.Tensor: shape=(), dtype=float64, numpy=6.708414106516358e-15>

In [5]:
tf.reduce_max(tf.math.abs(dictObj.qinv.L - output['L']))

<tf.Tensor: shape=(), dtype=float64, numpy=5.995206116204792e-15>

In [6]:
print(output['shift'])

tf.Tensor(1.9065862296939058e-13, shape=(), dtype=float64)


In [7]:
fid = open('iter_3_weights.pkl','rb')
output2 = pickle.load(fid)
fid.close()
dictObj2 = fctr.dictionary_object2D_init(fftSz = output2['fftSz'],D = output2['D'],rho = output2['rho'],objname = 'dictObj2',n_components = output2['n_components'])

In [8]:
tf.reduce_max(tf.math.abs(tf.complex(dictObj2.dhmul.Dfreal,dictObj2.dhmul.Dfimag) - output2['Dfprev']))

<tf.Tensor: shape=(), dtype=float64, numpy=6.7030864401088325e-15>

In [9]:
tf.reduce_max(tf.math.abs(dictObj2.qinv.L - output2['L']))

<tf.Tensor: shape=(), dtype=float64, numpy=5.995207174922142e-15>

In [10]:
print(output2['shift'])

tf.Tensor(1.8812616950290428e-13, shape=(), dtype=float64)


In [12]:
dictObj.dhmul.Dfreal = dictObj.dhmul.Dfreal.assign(dictObj2.dhmul.Dfreal)
dictObj.dhmul.Dfimag = dictObj.dhmul.Dfimag.assign(dictObj2.dhmul.Dfimag)
dictObj._dict_update()
print(dictObj.shift_test())

tf.Tensor(1.7763568394002505e-13, shape=(), dtype=float64)
