In [1]:
import tensorflow as tf

class OuterProd(tf.keras.layers.Layer):
    def __init__(self,*args,**kwargs):
        super().__init__(self,*args,**kwargs)
        
    def call(self,input1,input2):
        factor1 = tf.reshape(input1,shape=input1.shape + (1,))
        factor2 = tf.math.conj(tf.reshape(input2,shape=input2.shape[:-1] + (1,) + input2.shape[-1]))
        return factor1*factor2


In [2]:
import numpy as np

class MatrixAndVector(tf.keras.layers.Layer):
    def __init__(self,v=None,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.v = v

    def build(self,input_shape):
        if self.v is not None:
            self.V = tf.Variable(initial_value=self.v,trainable=True,dtype=self.dtype)
        else:
            self.V = tf.Variable(initial_value=tf.random.normal(shape=(1,) + input_shape[1:]),trainable=True,dtype=self.dtype)
        self.setupA(input_shape,self.V)
        
    def setupA(self,input_shape,V):
        idmat = tf.eye(num_rows=input_shape[-1],batch_shape=(1,) + input_shape[1:-1],dtype=self.dtype)
        self.L = tf.Variable(initial_value = tf.linalg.cholesky(idmat + OuterProd(dtype=self.dtype)(self.V,self.V)), trainable = False,dtype=self.dtype)        
    def applyA(self,x):
        return tf.linalg.matvec(self.L,tf.linalg.matvec(self.L,x,adjoint_a=True))
    def call(self, inputs):
        Ax = self.applyA(inputs)
        vvhx = tf.reduce_sum(inputs*tf.math.conj(self.V),axis=-1,keepdims=True)*self.V
        return  Ax + vvhx


v_init = np.zeros(shape=(1,2))
v_init[slice(None),0] = 1
                             
x = tf.keras.layers.Input((2,))
ApVVh= MatrixAndVector(v_init)
y = ApVVh(x)
model = tf.keras.Model(x,y)
model.compile(optimizer = tf.keras.optimizers.SGD(),loss=tf.keras.losses.MeanSquaredError())

x_train=np.random.randn(1000,2)
y_train = 2*x_train
x_val=np.random.randn(100,2)
y_val = 2*x_val
model.fit(x=x_train,y=y_train,batch_size=10,epochs=16,validation_data=(x_val,y_val))
ApVVh.V
                             

Epoch 1/16
100/100 [==============================] - 0s 2ms/step - loss: 0.5725 - val_loss: 0.6199
Epoch 2/16
100/100 [==============================] - 0s 880us/step - loss: 0.4739 - val_loss: 0.5757
Epoch 3/16
100/100 [==============================] - 0s 928us/step - loss: 0.3189 - val_loss: 0.1571
Epoch 4/16
100/100 [==============================] - 0s 912us/step - loss: 0.0318 - val_loss: 0.0021
Epoch 5/16
100/100 [==============================] - 0s 863us/step - loss: 4.5103e-04 - val_loss: 3.3355e-05
Epoch 6/16
100/100 [==============================] - 0s 767us/step - loss: 8.3255e-06 - val_loss: 6.5757e-07
Epoch 7/16
100/100 [==============================] - 0s 873us/step - loss: 1.6540e-07 - val_loss: 1.2799e-08
Epoch 8/16
100/100 [==============================] - 0s 894us/step - loss: 3.2806e-09 - val_loss: 2.5367e-10
Epoch 9/16
100/100 [==============================] - 0s 826us/step - loss: 6.5189e-11 - val_loss: 5.1506e-12
Epoch 10/16
100/100 [=======================

<tf.Variable 'matrix_and_vector/Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1.5817825e-08, 9.9999988e-01]], dtype=float32)>

In [4]:
ApVVh.dtype

'float32'

In [3]:
class PostProcess:
    update = {}
class CustomTrainModel(tf.keras.Model):
    def train_step(self,data):
        myoutputs = tf.keras.Model.train_step(self,data)
        for tv in self.trainable_variables:
            if tv.name in PostProcess.update:
                PostProcess.update[tv.name]()
        return myoutputs

In [75]:
def eigvecReversal(U,V):
    vtv = tf.reduce_sum(V*V,axis=-1,keepdims=True)
    utu = tf.reduce_sum(U*U,axis=-1,keepdims=True)
    utv = tf.reduce_sum(U*V,axis=-1,keepdims=True)
    utvs = tf.reshape(utv,utv.shape[:-1])
    rootRadicand = tf.math.sqrt(vtv*utu)
    rootRadicands = tf.reshape(rootRadicand,rootRadicand.shape[:-1])
        
    valPlus = utvs + rootRadicands
    valMinus = utvs - rootRadicands
    vecPlus = vtv*U + rootRadicand*V
    vecMinus = vtv*U - rootRadicand*V
    #vecPlus = tf.where(tf.abs(rootRadicand) > 1e-5,vecPlus,U)
    #vecMinus = tf.where(tf.abs(rootRadicand) > 1e-5,vecMinus,-tf.math.divide_no_nan(utv,utu)*U + V)
    #tf.debugging.Assert(condition=tf.abs(rootRadicands) > 1e-5,data=rootRadicands)
        
    vecPlus = tf.math.l2_normalize(vecPlus,epsilon=1e-5)
    vecMinus = tf.math.l2_normalize(vecMinus,epsilon=1e-5)
    return ((valPlus,valMinus),(vecPlus,vecMinus))
 

In [12]:
U = tf.random.normal((1,2))
V = tf.random.normal((1,2))
eigvals,eigvecs = eigvecReversal(U,V)

In [13]:
A = OuterProd()(U,V) + OuterProd()(V,U)
print(A)
A_again = eigvals[0]*OuterProd()(eigvecs[0],eigvecs[0]) + eigvals[1]*OuterProd()(eigvecs[1],eigvecs[1])
print(A_again)

tf.Tensor(
[[[-1.8185118   0.5211488 ]
  [ 0.5211488   0.77038383]]], shape=(1, 2, 2), dtype=float32)
tf.Tensor(
[[[-1.8185118  0.5211488]
  [ 0.5211488  0.7703838]]], shape=(1, 2, 2), dtype=float32)


In [9]:


import tensorflow_probability as tfp

class NewMatrixAndVector(MatrixAndVector):
    def build(self,input_shape):
        super().build(input_shape)
    def setupA(self,input_shape,V):
        idmat = tf.eye(num_rows=input_shape[-1],batch_shape=(1,) + input_shape[1:-1],dtype=self.dtype)
        self.A = tf.Variable(initial_value = idmat + OuterProd(dtype=self.dtype)(self.V,self.V), trainable = False)
    def applyA(self,x):
        return tf.linalg.matvec(self.A,x)

v_init = np.zeros(shape=(1,2))
v_init[slice(None),0] = 1

ApVVh= NewMatrixAndVector(v_init)
                             
x = tf.keras.layers.Input((2,))
y = ApVVh(x)
model = CustomTrainModel(x,y)
model.compile(optimizer=tf.keras.optimizers.SGD(),loss=tf.keras.losses.MeanSquaredError(),run_eagerly=False)

x_train=np.random.randn(1000,2)
y_train = 2*x_train
x_val=np.random.randn(100,2)
y_val = 2*x_val
model.fit(x=x_train,y=y_train,batch_size=10,epochs=16,validation_data=(x_val,y_val))
ApVVh.V

Epoch 1/16
100/100 [==============================] - 0s 1ms/step - loss: 0.5707 - val_loss: 0.4725
Epoch 2/16
100/100 [==============================] - 0s 870us/step - loss: 0.4767 - val_loss: 0.4467
Epoch 3/16
100/100 [==============================] - 0s 914us/step - loss: 0.3792 - val_loss: 0.2067
Epoch 4/16
100/100 [==============================] - 0s 907us/step - loss: 0.0652 - val_loss: 0.0039
Epoch 5/16
100/100 [==============================] - 0s 852us/step - loss: 9.5699e-04 - val_loss: 6.3413e-05
Epoch 6/16
100/100 [==============================] - 0s 808us/step - loss: 1.7138e-05 - val_loss: 1.2715e-06
Epoch 7/16
100/100 [==============================] - 0s 846us/step - loss: 3.4603e-07 - val_loss: 2.5757e-08
Epoch 8/16
100/100 [==============================] - 0s 808us/step - loss: 7.0086e-09 - val_loss: 5.2393e-10
Epoch 9/16
100/100 [==============================] - 0s 872us/step - loss: 1.4275e-10 - val_loss: 1.0633e-11
Epoch 10/16
100/100 [=======================

<tf.Variable 'new_matrix_and_vector/Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 1.1247319e-08, -9.9999994e-01]], dtype=float32)>

In [15]:


import tensorflow_probability as tfp

class NewMatrixAndVector(MatrixAndVector,PostProcess):
    def build(self,input_shape):
        super().build(input_shape)
        self.Vfixed = tf.Variable(initial_value=tf.identity(self.V),trainable=False,dtype=self.dtype)
        PostProcess.update[self.V.name] = self.post_update
    def setupA(self,input_shape,V):
        idmat = tf.eye(num_rows=input_shape[-1],batch_shape=(1,) + input_shape[1:-1],dtype=self.dtype)
        self.A = tf.Variable(initial_value = idmat + OuterProd(dtype=self.dtype)(self.V,self.V), trainable = False)
    def applyA(self,x):
        return tf.linalg.matvec(self.A,x)
    def updateA(self,u_vec,mult):
        return self.A.assign(self.A + mult*OuterProd(dtype=self.dtype)(u_vec,u_vec))
    def post_update(self):
        U = self.V - self.Vfixed
        with tf.control_dependencies([U]):
            self.V.assign(self.Vfixed)
        newA = self.updateA(U,1.0)
        eigvals, eigvecs = eigvecReversal(U,self.Vfixed)
        for ii in range(2):
            with tf.control_dependencies([newA]):
                newA = self.updateA(eigvecs[ii],eigvals[ii])

v_init = np.zeros(shape=(1,2))
v_init[slice(None),0] = 1

ApVVh= NewMatrixAndVector(v_init)
                             
x = tf.keras.layers.Input((2,))
y = ApVVh(x)
model = CustomTrainModel(x,y)
model.compile(optimizer=tf.keras.optimizers.SGD(0.2),loss=tf.keras.losses.MeanSquaredError(),run_eagerly=False)

x_train=np.random.randn(1000,2)
y_train = 2*x_train
x_val=np.random.randn(100,2)
y_val = 2*x_val
model.fit(x=x_train,y=y_train,batch_size=10,epochs=16,validation_data=(x_val,y_val))
ApVVh.V

Epoch 1/16
100/100 [==============================] - 0s 1ms/step - loss: 0.3161 - val_loss: 0.2286
Epoch 2/16
100/100 [==============================] - 0s 893us/step - loss: 0.1446 - val_loss: 0.1330
Epoch 3/16
100/100 [==============================] - 0s 900us/step - loss: 0.0913 - val_loss: 0.0807
Epoch 4/16
100/100 [==============================] - 0s 903us/step - loss: 0.0596 - val_loss: 0.0569
Epoch 5/16
100/100 [==============================] - 0s 917us/step - loss: 0.0433 - val_loss: 0.0391
Epoch 6/16
100/100 [==============================] - 0s 876us/step - loss: 0.0312 - val_loss: 0.0319
Epoch 7/16
100/100 [==============================] - 0s 906us/step - loss: 0.0259 - val_loss: 0.0264
Epoch 8/16
100/100 [==============================] - 0s 889us/step - loss: 0.0213 - val_loss: 0.0217
Epoch 9/16
100/100 [==============================] - 0s 935us/step - loss: 0.0179 - val_loss: 0.0181
Epoch 10/16
100/100 [==============================] - 0s 879us/step - loss: 0.0153 

<tf.Variable 'new_matrix_and_vector_4/Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 0.]], dtype=float32)>

In [18]:
print(ApVVh.A)

AttributeError: 'NewMatrixAndVector' object has no attribute 'A'

In [76]:


import tensorflow_probability as tfp

class NewMatrixAndVector(MatrixAndVector,PostProcess):
    def build(self,input_shape):
        super().build(input_shape)
        self.Vfixed = tf.Variable(initial_value=tf.identity(self.V),trainable=False,dtype=self.dtype)
        PostProcess.update[self.V.name] = self.post_update
    def updateA(self,u_vec,mult):
        return self.L.assign(tfp.math.cholesky_update(self.L,update_vector=u_vec,multiplier=mult))
    def post_update(self):
        U = self.V - self.Vfixed
        #print(U)
        with tf.control_dependencies([U]):
            self.V.assign(self.Vfixed)
        newA = self.updateA(U,1.0)
        #print(tf.matmul(newA,newA,adjoint_b=True))
        eigvals, eigvecs = eigvecReversal(U,self.Vfixed)
        for ii in range(2):
            with tf.control_dependencies([newA]):
                newA = self.updateA(eigvecs[ii],eigvals[ii])

v_init = np.zeros((1,2))
b = np.zeros(shape=(1,2))
b[slice(None),0] = 1
v_init[slice(None),0] = 1

ApVVh= NewMatrixAndVector(v_init)
                             
x = tf.keras.layers.Input((2,))
y = ApVVh(x)
model = CustomTrainModel(x,y)
model.compile(optimizer=tf.keras.optimizers.SGD(0.2),loss=tf.keras.losses.MeanSquaredError(),run_eagerly=False)

x_train=np.random.randn(1000,2)
y_train = 2*x_train
x_val=np.random.randn(100,2)
y_val = 2*x_val
model.fit(x=x_train,y=y_train,batch_size=10,epochs=16,validation_data=(x_val,y_val))
ApVVh.V

Epoch 1/16
100/100 [==============================] - 0s 2ms/step - loss: 0.3534 - val_loss: 0.1727
Epoch 2/16
100/100 [==============================] - 0s 2ms/step - loss: 0.1708 - val_loss: 0.0833
Epoch 3/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0863 - val_loss: 0.0519
Epoch 4/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0542 - val_loss: 0.0309
Epoch 5/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0351 - val_loss: 0.0223
Epoch 6/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0255 - val_loss: 0.0164
Epoch 7/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0190 - val_loss: 0.0125
Epoch 8/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0154 - val_loss: 0.0105
Epoch 9/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0128 - val_loss: 0.0087
Epoch 10/16
100/100 [==============================] - 0s 2ms/step - loss: 0.0112 - val_loss: 0.0079

<tf.Variable 'new_matrix_and_vector_49/Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 0.]], dtype=float32)>

In [8]:
print(tf.linalg.matmul(ApVVh.L,ApVVh.L,adjoint_b=True))

tf.Tensor(
[[[1.00850006+0.j         0.0021042 +0.00019345j]
  [0.0021042 -0.00019345j 1.34594523+0.j        ]]], shape=(1, 2, 2), dtype=complex128)


In [4]:
def complexNum(x):
    return tf.complex(x,tf.cast(0.0,dtype = x.dtype))

def eigvecReversal(U,V):
    vhv = tf.reduce_sum(tf.math.conj(V)*V,axis=-1,keepdims=True)
    uhu = tf.reduce_sum(tf.math.conj(U)*U,axis=-1,keepdims=True)
    uhv = tf.reduce_sum(tf.math.conj(U)*V,axis=-1,keepdims=True)
    rootRadicand = tf.math.sqrt(vhv*uhu - complexNum(tf.math.imag(uhv)**2))
        
    valPlus = complexNum(tf.math.real(uhv)) + rootRadicand
    valMinus = complexNum(tf.math.real(uhv)) - rootRadicand
    vecPlus = vhv*U + (1j*complexNum(tf.math.imag(uhv)) + rootRadicand)*V
    vecMinus = vhv*U + (1j*complexNum(tf.math.imag(uhv))  - rootRadicand)*V
    vecPlus = tf.where(tf.abs(rootRadicand) > 1e-5,vecPlus,U)
    vecMinus = tf.where(tf.abs(rootRadicand) > 1e-5,vecMinus,-tf.math.divide_no_nan(uhv,uhu)*U + V)
    #tf.debugging.Assert(condition=tf.abs(rootRadicands) > 1e-5,data=rootRadicands)
        
    vecPlus = tf.math.l2_normalize(vecPlus,epsilon=1e-5)
    vecMinus = tf.math.l2_normalize(vecMinus,epsilon=1e-5)
    valPlus = tf.reshape(valPlus,valPlus.shape[:-1])
    valMinus = tf.reshape(valMinus,valMinus.shape[:-1])
    return ((valPlus,valMinus),(vecPlus,vecMinus))
 

In [64]:
U = tf.complex(tf.random.normal((1,2)),tf.random.normal((1,2)))
V = tf.complex(tf.random.normal((1,2)),tf.random.normal((1,2)))
eigvals,eigvecs = eigvecReversal(U,V)

In [65]:
A = OuterProd()(U,V) + OuterProd()(V,U)
print(A)
A_again = eigvals[0]*OuterProd()(eigvecs[0],eigvecs[0]) + eigvals[1]*OuterProd()(eigvecs[1],eigvecs[1])
print(A_again)

tf.Tensor(
[[[ 1.3619424 +0.j         -0.34927106+0.65208745j]
  [-0.34927106-0.65208745j -0.63275087+0.j        ]]], shape=(1, 2, 2), dtype=complex64)
tf.Tensor(
[[[ 1.3619424 +0.j        -0.34927112+0.6520874j]
  [-0.34927112-0.6520874j -0.632751  +0.j       ]]], shape=(1, 2, 2), dtype=complex64)


In [1]:
def complexNum(x):
    return tf.complex(x,tf.cast(0.0,dtype = x.dtype))

In [7]:
import tensorflow_probability as tfp
class NewMatrixAndVector(MatrixAndVector,PostProcess):
    def build(self,input_shape):
        super().build(input_shape)
        self.Vfixed = tf.Variable(initial_value=tf.identity(self.V),trainable=False,dtype=self.dtype)
        PostProcess.update[self.V.name] = self.post_update
    def updateA(self,u_vec,mult):
        return self.L.assign(tfp.math.cholesky_update(self.L,update_vector=u_vec,multiplier=mult))
    def post_update(self):
        U = self.V - self.Vfixed
        with tf.control_dependencies([U]):
            self.V.assign(self.Vfixed)
        newA = self.updateA(U,1.0)
        eigvals, eigvecs = eigvecReversal(U,self.Vfixed)
        for ii in range(2):
            with tf.control_dependencies([newA]):
                newA = self.updateA(eigvecs[ii],eigvals[ii])

v_a = np.zeros((1,2))
v_a[slice(None),0] = 1
v_b = np.zeros(shape=(1,2))
#v_b[slice(None),1] = 0.5
v_init = tf.complex(v_a,v_b)

ApVVh= NewMatrixAndVector(v_init,dtype=tf.complex128)

                             
x = tf.keras.layers.Input((2,),dtype = tf.complex128)
y = ApVVh(x)
model = CustomTrainModel(x,y)
model.compile(optimizer=tf.keras.optimizers.SGD(.1),loss=tf.keras.losses.MeanSquaredError(),run_eagerly=False)

x_train=np.random.randn(1000,2) + 1j*np.random.randn(1000,2)
y_train = 2*x_train
x_val=np.random.randn(100,2) + 1j*np.random.randn(100,2)
y_val = 2*x_val
model.fit(x=x_train,y=y_train,batch_size=10,epochs=16,validation_data=(x_val,y_val))
ApVVh.V

Epoch 1/16
100/100 [==============================] - 0s 2ms/step - loss: 1.0025 - val_loss: 0.8515
Epoch 2/16
100/100 [==============================] - 0s 2ms/step - loss: 0.9445 - val_loss: 1.0328
Epoch 3/16
100/100 [==============================] - 0s 2ms/step - loss: 0.9699 - val_loss: 0.9899
Epoch 4/16
100/100 [==============================] - 0s 1ms/step - loss: 1.1846 - val_loss: 1.2318
Epoch 5/16
100/100 [==============================] - 0s 2ms/step - loss: 1.0773 - val_loss: 0.8459
Epoch 6/16
100/100 [==============================] - 0s 2ms/step - loss: 0.9425 - val_loss: 0.9193
Epoch 7/16
100/100 [==============================] - 0s 2ms/step - loss: 0.8931 - val_loss: 0.8199
Epoch 8/16
100/100 [==============================] - 0s 2ms/step - loss: 0.7126 - val_loss: 0.6390
Epoch 9/16
100/100 [==============================] - 0s 2ms/step - loss: 0.6638 - val_loss: 0.6238
Epoch 10/16
100/100 [==============================] - 0s 2ms/step - loss: 0.5381 - val_loss: 0.4901

<tf.Variable 'new_matrix_and_vector_1/Variable:0' shape=(1, 2) dtype=complex128, numpy=array([[1.+0.j, 0.+0.j]])>