In [1]:
import tensorflow as tf
import matrix_decompositions_tf as fctr

dict = tf.convert_to_tensor([[0.,0.,0.],[0.,0.,0.],[0.,1.,0.]],dtype = tf.float64)

In [2]:
dict = tf.reshape(dict,shape = (3,3,1,1))


In [3]:
print(tf.reshape(dict,shape=(3,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]], shape=(3, 3), dtype=float64)


In [4]:
x = tf.convert_to_tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 1., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 0.]])

x = tf.reshape(x,shape=(1,8,8,1,1))

In [5]:
divide_by_R = fctr.Coef_Divide_By_R(tf.reshape(dict,(1,3,3,1,1)),noc = 1,dtype=tf.float64)

In [6]:
mulD_sp = fctr.MulD_Sp(divide_by_R,dtype=tf.float64)
mulDt_sp = fctr.MulDT_Sp(divide_by_R,dtype=tf.float64)

In [7]:
y = mulD_sp(mulDt_sp(x))

In [8]:
print(tf.reshape(x,(8,8)))

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(8, 8), dtype=float32)


In [9]:
print(tf.reshape(y,(8,8)))

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]], shape=(8, 8), dtype=float64)
