In [1]:
import pickle as pkl
fid = open('data/experiment/BSDS500/experiment1/ML_LRA_results.pkl','rb')

my_tuple = pkl.load(fid)
fid.close()
times,results1,results2,results3 = my_tuple

In [6]:
results1


[{'loss': 0.011113808490335941, 'mean_squared_error': 0.011113807793426108},
 {'loss': 0.004167885985225439, 'mean_squared_error': 0.004167885825209933},
 {'loss': 0.0028790654614567757, 'mean_squared_error': 0.0028790655472982155},
 {'loss': 0.00286986050195992, 'mean_squared_error': 0.0028698603837291176},
 {'loss': 0.0028731231577694416, 'mean_squared_error': 0.00287312278844939},
 {'loss': 0.002840799279510975, 'mean_squared_error': 0.002840799402909019},
 {'loss': 0.002842584392055869, 'mean_squared_error': 0.0028425849918680087},
 {'loss': 0.002749351318925619, 'mean_squared_error': 0.0027493522742772104},
 {'loss': 0.002747849328443408, 'mean_squared_error': 0.0027478493735379407}]

In [5]:
results2

[{'loss': 0.011113272979855537},
 {'loss': 0.004338390659540892},
 {'loss': 0.002904318505898118},
 {'loss': 0.0028927389066666365},
 {'loss': 0.002896898426115513},
 {'loss': 0.002855806378647685},
 {'loss': 0.002858137246221304},
 {'loss': 0.0027349700685590506},
 {'loss': 0.0027329016011208296}]

In [4]:
results3

[{'loss': 0.011113540269434452},
 {'loss': 0.004249878227710724},
 {'loss': 0.0028841423336416483},
 {'loss': 0.0028736679814755917},
 {'loss': 0.002877411898225546},
 {'loss': 0.002840384840965271},
 {'loss': 0.002842465415596962},
 {'loss': 0.0027330033481121063},
 {'loss': 0.0027311902958899736}]

In [7]:
import pickle as pkl
fid = open('data/experiment/BSDS500/experiment1/ML_FISTA_results.pkl','rb')

my_tuple = pkl.load(fid)
fid.close()
times_FISTA,results1_FISTA,results2_FISTA,results3_FISTA = my_tuple

In [9]:
results1_FISTA

[{'loss': 0.004232683219015598, 'mean_squared_error': 0.00423268314390584},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362},
 {'loss': 0.0022798485588282347, 'mean_squared_error': 0.0022798481092909362}]

In [10]:
results2_FISTA

[{'loss': 0.0033563983161002398},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358},
 {'loss': 0.00191781937610358}]

In [11]:
results3_FISTA

[{'loss': 0.0037707972805947065},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115},
 {'loss': 0.0019458538154140115}]

In [12]:
times

{'afterdrift_dict_layer1/dhmul/Dfreq_real:0': [<tf.Tensor: shape=(), dtype=float64, numpy=1.777777356891875e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.6396697384179932e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.6889408021831845e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=2.1610313646285635e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=2.327502010382318e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.706782221257344e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=2.1363599072362985e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=2.13347777657168e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.8487770363517607e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.8736144289136713e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.877231854567598e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.8312851990543594e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.8528687647866062e-13>,
  <tf.Tensor: shape=(), dtype=float64, numpy=1.9319

In [13]:
times_FISTA

{'iterations': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96]}