In [1]:
import tensorflow as tf
import util

x = tf.convert_to_tensor([[[1.,2.,3.,4.,5.,6.,7.,8.],[5.,6.,7.,8.,9.,10.,11.,12.],[9.,10.,11.,12.,13.,14.,15.,16.],[13.,14.,15.,16.,17,18.,19.,20.],[17.,18.,19.,20.,21.,22.,23.,24.],[21.,22.,23.,24.,25.,26,27.,28.]]])
print(x)
#,[17,18,19,20],[21,22,23,24],[25,26,27,28]]])

tf.Tensor(
[[[ 1.  2.  3.  4.  5.  6.  7.  8.]
  [ 5.  6.  7.  8.  9. 10. 11. 12.]
  [ 9. 10. 11. 12. 13. 14. 15. 16.]
  [13. 14. 15. 16. 17. 18. 19. 20.]
  [17. 18. 19. 20. 21. 22. 23. 24.]
  [21. 22. 23. 24. 25. 26. 27. 28.]]], shape=(1, 6, 8), dtype=float32)


In [2]:
import transforms as transf
xf = transf.fft2d_inner((6,8))(tf.reshape(x,(1,6,8,1,1)))

In [3]:
xf.shape

TensorShape([1, 6, 5, 1, 1])

In [6]:
x_downsample = transf.ifft2d_inner((3,4))(util.freq_downsample(xf))

In [5]:
print(x_downsample)

tf.Tensor(
[[[[[ 50.666668]]

   [[ 53.091274]]

   [[ 64.24206 ]]]


  [[[ 72.      ]]

   [[ 74.42461 ]]

   [[ 85.57539 ]]]


  [[[ 93.33334 ]]

   [[ 95.75796 ]]

   [[106.90874 ]]]]], shape=(1, 3, 3, 1, 1), dtype=float32)


In [7]:
print(tf.squeeze(x_downsample,axis=[-2,-1]))

tf.Tensor(
[[[ 1.0000012  3.0000005  5.000001   7.0000014]
  [ 9.000001  10.999999  12.999999  15.000001 ]
  [17.        19.        21.        23.       ]]], shape=(1, 3, 4), dtype=float32)
