In [1]:
import PIL
import PIL.Image

In [2]:
im = PIL.Image.open('20190728_matthewdruincom_SLE_0033.jpg')

In [5]:
im.quantization

{0: array('B', [2, 2, 2, 3, 2, 3, 4, 2, 2, 4, 5, 4, 3, 4, 5, 6, 5, 5, 5, 5, 6, 8, 7, 7, 7, 7, 7, 8, 11, 9, 9, 9, 9, 9, 9, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]),
 1: array('B', [3, 3, 3, 7, 4, 7, 13, 7, 7, 13, 15, 13, 13, 13, 15, 15, 14, 14, 14, 14, 15, 15, 12, 12, 12, 12, 12, 15, 15, 12, 12, 12, 12, 12, 12, 15, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])}

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
image = PIL.Image.open("20190728_matthewdruincom_SLE_0033.jpg")
s = np.asarray(image)
s = s[slice(1006,1038),slice(1352,1384),slice(None)]
croppedImage = PIL.Image.fromarray(s,'RGB')
#croppedImage.show()
#print(s.shape)

In [5]:
image2 = tf.image.encode_jpeg(s,quality=25)
tf.io.write_file('jpeg25.jpg',image2)
im25 = PIL.Image.open('jpeg25.jpg')


In [15]:
im25 = PIL.Image.open('jpeg25.jpg')
#print(im25.quantization)
a = np.reshape(range(64),(8,8))
qY = np.asarray(im25.quantization[0]).astype('uint8')
qUV = np.asarray(im25.quantization[1]).astype('uint8')

a = np.concatenate([np.diagonal(a[::-1,:], k)[::(2*(k % 2)-1)] for k in range(1-a.shape[0], a.shape[0])])
#qY = qY[a]
#qUV = qUV[a]
print(np.reshape(qY,(8,8)))
print(np.reshape(qUV,(8,8)))

[[ 32  22  24  28  24  20  32  28]
 [ 26  28  36  34  32  38  48  80]
 [ 52  48  44  44  48  98  70  74]
 [ 58  80 116 102 122 120 114 102]
 [112 110 128 144 184 156 128 136]
 [174 138 110 112 160 218 162 174]
 [190 196 206 208 206 124 154 226]
 [242 224 200 240 184 202 206 198]]
[[ 34  36  36  48  42  48  94  52]
 [ 52  94 198 132 112 132 198 198]
 [198 198 198 198 198 198 198 198]
 [198 198 198 198 198 198 198 198]
 [198 198 198 198 198 198 198 198]
 [198 198 198 198 198 198 198 198]
 [198 198 198 198 198 198 198 198]
 [198 198 198 198 198 198 198 198]]


In [21]:
croppedImage.save('jpeg25.jpg',quality=1)