In [1]:
import tensorflow as tf
import jpeg_related_functions as jrf

In [2]:
#x = tf.random.uniform(shape=(5,128,128,3))
rgb2jpeg_coef = jrf.RGB2JPEG_Coef()
jpeg_coef2rgb = jrf.JPEG_Coef2RGB()

In [2]:
y = jpeg_coef2rgb(rgb2jpeg_coef(x))
z = jpeg_coef2rgb(rgb2jpeg_coef(x))

NameError: name 'jpeg_coef2rgb' is not defined

In [3]:
from PIL import Image
image = Image.open("20190728_matthewdruincom_SLE_0033.jpg")
#image = Image.open("20200202_matthewdruincom_SLW_0085.jpg")
#image.show()
import numpy as np
x_orig = np.asarray(image).astype('float64')

x_batch = np.reshape(x_orig.astype('float64')/255.,(1,)+x_orig.shape)
x_batch = x_batch[slice(None),slice(0,1600),slice(0,2800),slice(None)]
x = (np.reshape(x_batch,x_batch.shape[1:])*255.).astype('uint8')
x_orig = Image.fromarray(x)
x_cmprss = tf.image.adjust_jpeg_quality(x,15)
image_cmprss = Image.fromarray(np.asarray(x_cmprss),'RGB')
image_cmprss.show()
x_cmprss_batch = np.reshape(np.asarray(x_cmprss).astype('float64')/255.,(1,)+x_cmprss.shape)
#x_cmprss_apprx = jrf.Linear_JPEG_Compression_Approx(x_cmprss_batch)(x_batch)
#image_cmprss_apprx = Image.fromarray(np.asarray(x_cmprss_apprx*255).astype('uint8'),'RGB')
#image_cmprss_apprx.show

#y = jpeg_coef2rgb(rgb2jpeg_coef(x))
#z = jpeg_coef2rgb(rgb2jpeg_coef(x))

In [4]:
print(x_batch.shape)
print(x_cmprss_batch.shape)

(1, 1600, 2800, 3)
(1, 1600, 2800, 3)


In [4]:
x_cmprss_apprx = jrf.Linear_JPEG_Compression_Approx(x_cmprss_batch,epsilon=1e-3)(x_batch)
#print(tf.math.reduce_min(tf.where(jrf.Linear_JPEG_Compression_Approx(x_cmprss_batch).masky,1.0,0.0)))


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [5]:
x_cmprss_apprx_clipped = tf.where(x_cmprss_apprx < 0,0.,x_cmprss_apprx)
x_cmprss_apprx_clipped = tf.where(x_cmprss_apprx > 1.0,1.0,x_cmprss_apprx_clipped)
image_cmprss_apprx = Image.fromarray(np.asarray(tf.reshape(x_cmprss_apprx_clipped,x_cmprss_apprx.shape[1:])*255).astype('uint8'),'RGB')
image_cmprss_apprx.show()

In [6]:
print(tf.math.reduce_max(x_cmprss_apprx))

tf.Tensor(1.0698118, shape=(), dtype=float32)


In [7]:
tf.math.reduce_min(y)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [4]:
print(tf.math.reduce_max(tf.math.abs(x - y)))
print(tf.math.reduce_max(tf.math.abs(z - y)))

tf.Tensor(0.21713108, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [5]:
x.shape

TensorShape([5, 128, 128, 3])

In [5]:
x[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.22571766>

In [6]:
y[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.4955484>