In [1]:
import tensorflow as tf


x = tf.zeros((12,12))
print(x)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(12, 12), dtype=float32)


In [5]:
print(tf.convert_to_tensor(range(12)))

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


In [7]:
x = tf.reshape(tf.convert_to_tensor(range(12)),(12,1))
x = tf.tile(x,[1,12])
print(x)

tf.Tensor(
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8  8  8  8]
 [ 9  9  9  9  9  9  9  9  9  9  9  9]
 [10 10 10 10 10 10 10 10 10 10 10 10]
 [11 11 11 11 11 11 11 11 11 11 11 11]], shape=(12, 12), dtype=int32)


In [12]:
y = tf.reshape(x,(3,4,12))
print(y[slice(None),slice(0,1),slice(None)])

tf.Tensor(
[[[0 0 0 0 0 0 0 0 0 0 0 0]]

 [[4 4 4 4 4 4 4 4 4 4 4 4]]

 [[8 8 8 8 8 8 8 8 8 8 8 8]]], shape=(3, 1, 12), dtype=int32)


In [46]:
x = tf.reshape(tf.convert_to_tensor(range(12),dtype='float32'),(1,12))
x = tf.tile(x,[12,1])
print(x)

tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]], shape=(12, 12), dtype=float32)


In [19]:
print(x[slice(None),slice(0,1)])

tf.Tensor(
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]], shape=(12, 1), dtype=int32)


In [21]:
y = tf.reshape(x,(12,3,4))
print(tf.reshape(y[slice(None),slice(None),slice(0,1)],(12,3)))

tf.Tensor(
[[0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]
 [0 4 8]], shape=(12, 3), dtype=int32)


In [24]:
z = tf.reshape(x,(3,4,3,4))
print(tf.reshape(z[slice(None),slice(0,1),slice(None),slice(0,1)],(3,3)))


tf.Tensor(
[[0 4 8]
 [0 4 8]
 [0 4 8]], shape=(3, 3), dtype=int32)


In [54]:
x = tf.reshape(tf.convert_to_tensor(range(12),dtype='float32'),(12,1))
x = tf.tile(x,[1,12])
print(x)

tf.Tensor(
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]], shape=(12, 12), dtype=float32)


In [55]:
z = tf.reshape(x,(3,4,3,4))
print(tf.reshape(z[slice(None),slice(0,1),slice(None),slice(0,1)],(3,3)))

tf.Tensor(
[[0. 0. 0.]
 [4. 4. 4.]
 [8. 8. 8.]], shape=(3, 3), dtype=float32)


Add Rows

In [40]:
z = tf.reshape(x,(3,4,3,4))
z_sum = z[slice(None),slice(0,1),slice(None),slice(None)] + z[slice(None),slice(1,2),slice(None),slice(None)]
print(tf.reshape(z_sum,(3,12)))

tf.Tensor(
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]], shape=(3, 12), dtype=float32)


In [43]:
x = tf.reshape(tf.convert_to_tensor(range(12)),(1,12))
x = tf.tile(x,[12,1])
print(x)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]], shape=(12, 12), dtype=int32)


Add Cols

In [47]:
z = tf.reshape(x,(3,4,3,4))
z_sum = z[slice(None),slice(None),slice(None),slice(0,1)] + z[slice(None),slice(None),slice(None),slice(1,2)]
print(tf.reshape(z_sum,(12,3)))

tf.Tensor(
[[ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]
 [ 1.  9. 17.]], shape=(12, 3), dtype=float32)


In [42]:
a = 2.
b = 3.
row_sum1 = ((a + b)*z[slice(None),slice(0,1),slice(None),slice(None)] + b*z[slice(None),slice(1,2),slice(None),slice(None)])/(a + 2*b)
row_sum2 = (b*z[slice(None),slice(0,1),slice(None),slice(None)] + (a + b)*z[slice(None),slice(1,2),slice(None),slice(None)])/(a + 2*b)
newz = tf.concat([row_sum1,row_sum2,z[slice(None),slice(2,4),slice(None),slice(None)]],axis=1)
print(tf.reshape(newz,(12,12)))

tf.Tensor(
[[ 0.375  0.375  0.375  0.375  0.375  0.375  0.375  0.375  0.375  0.375
   0.375  0.375]
 [ 0.625  0.625  0.625  0.625  0.625  0.625  0.625  0.625  0.625  0.625
   0.625  0.625]
 [ 2.     2.     2.     2.     2.     2.     2.     2.     2.     2.
   2.     2.   ]
 [ 3.     3.     3.     3.     3.     3.     3.     3.     3.     3.
   3.     3.   ]
 [ 4.375  4.375  4.375  4.375  4.375  4.375  4.375  4.375  4.375  4.375
   4.375  4.375]
 [ 4.625  4.625  4.625  4.625  4.625  4.625  4.625  4.625  4.625  4.625
   4.625  4.625]
 [ 6.     6.     6.     6.     6.     6.     6.     6.     6.     6.
   6.     6.   ]
 [ 7.     7.     7.     7.     7.     7.     7.     7.     7.     7.
   7.     7.   ]
 [ 8.375  8.375  8.375  8.375  8.375  8.375  8.375  8.375  8.375  8.375
   8.375  8.375]
 [ 8.625  8.625  8.625  8.625  8.625  8.625  8.625  8.625  8.625  8.625
   8.625  8.625]
 [10.    10.    10.    10.    10.    10.    10.    10.    10.    10.
  10.    10.   ]
 [11.    11.    11.    11

In [56]:
a = 2.
b = 3.
col_sum1 = ((a + b)*z[slice(None),slice(None),slice(None),slice(0,1)] + b*z[slice(None),slice(None),slice(None),slice(1,2)])/(a + 2*b)
col_sum2 = (b*z[slice(None),slice(None),slice(None),slice(0,1)] + (a + b)*z[slice(None),slice(None),slice(None),slice(1,2)])/(a + 2*b)
newz = tf.concat([8. *col_sum1,8. *col_sum2,8. *z[slice(None),slice(None),slice(None),slice(2,4)]],axis=3)
print(tf.reshape(newz,(12,12)))

tf.Tensor(
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.]
 [32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32. 32.]
 [40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40.]
 [48. 48. 48. 48. 48. 48. 48. 48. 48. 48. 48. 48.]
 [56. 56. 56. 56. 56. 56. 56. 56. 56. 56. 56. 56.]
 [64. 64. 64. 64. 64. 64. 64. 64. 64. 64. 64. 64.]
 [72. 72. 72. 72. 72. 72. 72. 72. 72. 72. 72. 72.]
 [80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80.]
 [88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.]], shape=(12, 12), dtype=float32)


In [ ]:
tl_corner = newz[slice(None),slice(0,1),slice(None),slice(0,1)]

In [60]:
temp1 = tf.one_hot(indices = [[[0]]], depth = 4, on_value=1., off_value=0., axis=1, dtype='float32')
temp2 = tf.one_hot(indices = [[[0]]], depth = 4, on_value = 1., off_value= 0., axis = 3,dtype = 'float32')
selector = temp1*temp2

print(tf.reshape((1.0 - selector)*newz,(12,12)))

tf.Tensor(
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.]
 [ 0. 32. 32. 32.  0. 32. 32. 32.  0. 32. 32. 32.]
 [40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40.]
 [48. 48. 48. 48. 48. 48. 48. 48. 48. 48. 48. 48.]
 [56. 56. 56. 56. 56. 56. 56. 56. 56. 56. 56. 56.]
 [ 0. 64. 64. 64.  0. 64. 64. 64.  0. 64. 64. 64.]
 [72. 72. 72. 72. 72. 72. 72. 72. 72. 72. 72. 72.]
 [80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80.]
 [88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.]], shape=(12, 12), dtype=float32)


In [62]:
print(newz[slice(None),slice(1,-1),slice(None),slice(0,1)].shape)

(3, 2, 3, 1)


In [65]:
print(newz[slice(None),slice(1,-1)].shape)

(3, 2, 3, 4)


In [73]:
print(len(tf.one_hot(indices = tf.zeros((1,)*3,dtype='int32'), depth = 4, on_value=1., off_value=0., axis=1, dtype='float32').shape))

4


In [69]:
tf.zeros(4,dtype='int32')

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [75]:
slices = [slice(None),slice(-1,None)]
print(newz[slices[:]].shape)

(3, 1, 3, 4)
