In [1]:
a = 3.0
b = 2.0
x1 = 3.0
x2 = 4.0
x3 = 2.0
x4 = 3.0

Commented out lines use inverse to solve for z using x. Executed lines work "in place", relying on z for earlier indices, but x for current and future indices. This is more memory efficient, but allows less parallel computation.

In [2]:
z1 = 1./(a + 4*b)*((a**2 + 4*a*b + 2*b**2)/(a + 2*b)*x1 + b*x2 + b*x3 + 2*b**2/(a + 2*b)*x4)
#z2 = 1./(a + 4*b)*((a**2 + 4*a*b + 2*b**2)/(a + 2*b)*x2 + b*x1 + b*x4 + 2*b**2/(a + 2*b)*x3)
z2 = 1./(a**3 + 6*a**2*b + 10*a*b**2 + 4*b**3)*(b*(a+2*b)**2*z1 + a*(a + b)*(a + 3*b)*x2 +a*b**2*x3 + a*b*(a + 2*b)*x4)
#z3 = 1./(a + 4*b)*((a**2 + 4*a*b + 2*b**2)/(a + 2*b)*x3 + b*x1 + b*x4 + 2*b**2/(a + 2*b)*x2)
z3= 1./((a + b)*(a + 3*b))*(b*(a + 2*b)*z1 + b**2*z2 + a*(a + 2*b)*x3 + a*b*x4)
#z4 = 1./(a + 4*b)*((a**2 + 4*a*b + 2*b**2)/(a + 2*b)*x4 + b*x2 + b*x3 + 2*b**2/(a + 2*b)*x1)
z4 = 1./(a + 2*b)*(b*z2 + b*z3 + a*x4)

Same formulas, but pulling from jpeg_related_functions.

In [3]:
import jpeg_related_functions as jrf
fun_obj = jrf.I_dont_know_what_to_call_this(a,b)
z1 = fun_obj.get_TL(x1,x2,x3,x4)
z2 = fun_obj.get_TR(z1,x2,x3,x4)
z3 = fun_obj.get_BL(z1,z2,x3,x4)
z4 = fun_obj.get_BR(z1,z2,z3,x4)

All these expressions should be zero, if the above solution is correct.

In [4]:
print((a + 2*b)*z1 - a*x1 - b*z2 - b*z3)
print((a + 2*b)*z2 - a*x2 - b*z1 - b*z4)
print((a + 2*b)*z3 - a*x3 - b*z1 - b*z4)
print((a + 2*b)*z4 - a*x4 - b*z2 - b*z3)

0.0
0.0
0.0
0.0


In [5]:
z1 = ((a + b)*x1 + b*x2)/(a + 2*b)
z2 = (b*z1 + a*x2)/(a + b)
#z2 = (b*x1 + (a + b)*x2)/(a + 2*b)

In [6]:
print((a + b)*z1 -b*z2 - a*x1)
print(-b*z1 + (a + b)*z2 - a*x2)

0.0
-1.7763568394002505e-15


In [7]:
import tensorflow as tf
x = tf.zeros((12,12),dtype='float32')
print(x)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(12, 12), dtype=float32)


In [8]:
x[slice(0,12,4),slice(0,12,2)] = 1.
print(x)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment